# Generated by Django 4.1.3 on 2022-12-02 10:02

import cloudinary.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('date_created', models.DateTimeField(default=datetime.datetime(2022, 12, 2, 10, 2, 47, 458483, tzinfo=datetime.timezone.utc))),
                ('file', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True)),
                ('message', cloudinary.models.CloudinaryField(max_length=255, null=True)),
            ],
        ),
    ]
