# Generated by Django 4.1.3 on 2022-12-02 14:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_audio_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 2, 14, 59, 3, 863598, tzinfo=datetime.timezone.utc)),
        ),
    ]
