# Generated by Django 4.1.3 on 2022-12-05 08:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_audio_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 5, 8, 18, 14, 320690, tzinfo=datetime.timezone.utc)),
        ),
    ]
