# Generated by Django 4.1.3 on 2022-12-05 10:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_audio_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 5, 10, 58, 11, 487727, tzinfo=datetime.timezone.utc)),
        ),
    ]
