# Generated by Django 4.1.3 on 2022-12-05 13:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_audio_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 5, 13, 0, 14, 288029, tzinfo=datetime.timezone.utc)),
        ),
    ]
