# Generated by Django 4.1.3 on 2022-12-06 10:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_audio_date_created_alter_audio_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 6, 10, 46, 58, 38778, tzinfo=datetime.timezone.utc)),
        ),
    ]
