# Generated by Django 4.1.3 on 2022-12-05 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='created_by',
            new_name='user',
        ),
    ]
