# Generated by Django 4.1.3 on 2022-12-05 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_rename_created_by_document_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='created_by',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
